name: "\U0001F41B Bug Report"
description: "Report an issue or possible bug"
labels: [bug]
assignees: []
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I am willing to submit a pull request for this issue.
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: bug-expectation
    attributes:
      label: "What's the expected result?"
      description: Describe what you expect to happen.
    validations:
      required: true

  - type: input
    id: bug-reproduction
    attributes:
      label: Link to Minimal Reproducible Example
      description: "Use [StackBlitz](https://stackblitz.com/) or create a GitHub repo..."
      placeholder: "https://github.com/user/paraglide-repro"
    validations:
      required: true

  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this issue.
          required: false
